### ISSUE TITLE
Possible for other Sound?

### ISSUE THREAD

**Issue by dragoncamper** [sunnobunno/SunnysMod#1]
Is it possible to Change the sound which is used by this mod?
Using the mod with friends and we have a personal Sound file we would like to use instead of the yippe sound.

**Comment by sunnobunno** [comment]
Hi, you can if you're willing to do some work with Unity. The sound file is packaged in a unity assetbundle file. The details on how to do that are here: https://www.youtube.com/watch?v=eSCrZwairVw

The process is to import the sound into unity, tag it to be included in an asset bundle, then run a custom script (outlined in the video above) to generate the assetbundle file. If you name the sound you want to use the same as it is in the mod ("yippee-tbh.mp3"), export it in an assetbundle, and replace the mod's yippeesound file, the game will load the sound as if it were part of the mod.
